name: code check

on:
 push:
  branches:
      - main
jobs:
  checking:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install linter
      run: pip install flake8
    - name: run linter
      run: flake8 app.py
    - name: Install SAST
      run: pip install bandit
    - name: SAST run
      run: bandit -r app.py
      
