name: deploy-to-server

on:
    workflow_call:

jobs:
    deploy-to-server:
        runs-on: ubuntu-latest
        steps:
             - name: Remote SSH
               uses: appleboy/ssh-action@v1.0.3
               with:
                    host: ${{ secrets.EC2_SSH_HOST }}
                    username: ${{ secrets.EC2_SSH_USER }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    script: |
                     echo " Project will work"
                     mkdir -p Devops && sudo apt update && sudo apt-get install docker.io docker-compose-v2 -y
                     sudo usermod -aG docker $USER && newgrp docker

             - name: copy the docker compose file
               uses: appleboy/scp-action@v1
               with:
                   host: ${{ secrets.EC2_SSH_HOST }}
                   username: ${{ secrets.EC2_SSH_USER }}
                   key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                   source: dockercompose.yml
                   target: ~/Devops

             - name: Remote SSH ad run the app
               uses: appleboy/ssh-action@v1.0.3
               with:
                    host: ${{ secrets.EC2_SSH_HOST }}
                    username: ${{ secrets.EC2_SSH_USER }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    script: |
                     cd ~/devops
                     
                     docker compose down && docker compose up -d --build --force-recreate -pull always





        